### ISSUE TITLE
Austin Animal Center & Ohio Data (Pilot)

### ISSUE THREAD

**Issue by jkwening** [michaelgsuttles/saveallthepets#4]
Begin on "subproject" looking at already-collected data for Austin Animal Center and Ohio data, which includes outcomes.

Mike Herman will be working on the shelter data (2 shelters), doing EDA and then looking at which animals to hypothetically move from one shelter to the other. Pilot test

**Comment by michaelgsuttles** [comment]
No longer need to do this.
